### ISSUE TITLE
getCompetitivePricing调用问题

### ISSUE THREAD

**Issue by yingyuhaonan** [huanghuag/sp-api#1]
大佬，想问你个问题，我调用getCompetitivePricing的时候用asin请求信息是有返回的，但是用sku亚马逊就给我返回 ClientError，我能确保sku是正确的

**Comment by huanghuag** [comment]
传的入参是啥，有详细报错信息吗

**Comment by yingyuhaonan** [comment]
> 传的入参是啥，有详细报错信息吗

太久啦，这个需求没继续下去
